/**
 * 转换一个文件
 */

const fs = require('fs');
const transformToStyle = require('./transformToStyle');
const compile = require('./compile');
const chalk = require('chalk').default;
const { name: packageName } = require('../../package.json');

module.exports = (filepath) => {
  console.log(chalk.cyanBright('compile file -> ', filepath));
  try {
    const content = fs.readFileSync(filepath).toString('utf8');

    const result = compile(content);

    const cssStr = JSON.stringify(transformToStyle(result), null, 2);

    const jsFileContent = `
/**
 * This file is auto generated by ${packageName}
 * Please don't change any content
 */

const { StyleSheet } =  require('react-native');
const transCss =  require('${packageName}');

const styleStr = \`${cssStr}\`;

const build = (data) => {
  const _data = Object.assign({ hairlineWidth: StyleSheet.hairlineWidth }, data);
  return StyleSheet.create(transCss.render(styleStr, _data));
};

module.exports = {
  build,
};
    `;

    fs.writeFileSync(filepath.replace(/\..*/g, '.js'), jsFileContent);

    console.log(chalk.cyanBright('compile success -> ', filepath));
  } catch (e) {
    console.log(chalk.redBright(e.stack));
  }
};


